openapi: 3.0.3
info:
  title: Address Verification
  contact: {}
  version: '1.0'
  description: >
    # Overview
  
    This API enables your application to lookup the full address for a UK postcode.
    The results can be narrowed down by providing an optional filter, e.g. "21 High Street".
  
    Address data is provided by Ordnance Survey.
servers:
  - url: https://test-api.service.hmrc.gov.uk/misc/address-verification
    description: Sandbox
  - url: https://api.service.hmrc.gov.uk/misc/address-verification
    description: Production
paths:
  /lookup:
    post:
      summary: Lookup address
      description: >
        Lookup of postal and BFPO (British Forces Post Office) address details within the UK
      operationId: AddressVerificationLookup
      security:
        - applicationRestricted: [ ]
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: 'docs/post-request.json'
            example:
              postcode: "AA1 1ZZ"
              filter: "The Rectory"
        required: true
      responses:
        '200':
          description: ''
          headers: { }
          content:
            application/json:
              schema:
                $ref: 'docs/uk-address-object.json'
              example:
                [
                  {
                    "id": "GB200000706253",
                    "uprn": 200000706253,
                    "parentUprn": 200000706251,
                    "usrn": 300000706253,
                    "organisation": "Some Company",
                    "address": {
                      "lines": [
                        "Test House",
                        "The Tests"
                      ],
                      "town": "Test Town",
                      "postcode": "BB00 0BB",
                      "subdivision": {
                        "code": "GB-ENG",
                        "name": "England"
                      },
                      "country": {
                        "code": "GB",
                        "name": "United Kingdom"
                      }
                    },
                    "localCustodian": {
                      "code": 1760,
                      "name": "Test Valley"
                    },
                    "location": [
                      50.9986451,
                      -1.4690977
                    ],
                    "language": "en",
                    "administrativeArea": "TEST COUNTY"
                  }
                ]
        3XX:
          description: |
            The request has been redirected. Clients should follow the redirect using the location header as per the HTTP specification.
        400:
          description: |
            The request was invalid, e.g the the postcode is not well formed.
        5XX:
          description: |
            An unexpected server error occurred when processing the request. These are usually temporary and consumers should try again.
      deprecated: false
components:
  securitySchemes:
    applicationRestricted:
      type: oauth2
      description: |
        HMRC supports OAuth 2.0 for authenticating application restricted API requests using an OAuth 2.0 Bearer Token in the AUTHORIZATION header.
        See https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/application-restricted-endpoints for details.
      flows:
        clientCredentials:
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          scopes: { }
