#%RAML 1.0
---
title: Address Lookup
version: 1.0

protocols: [ HTTPS ]
baseUri: https://address-lookup.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md

mediaType: application/hal+json

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

/lookup:
  /address:
    get:
      displayName: Lookup address
      description: |
        Lookup of postal and BFPO (British Forces Post Office) address details within the UK
      is: [headers.acceptHeader]
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "message" : "Hello World"
                }